# -*- coding: utf-8 -*-
"""Belajar_Coding_Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OoMl7w_AgQYvEtUiBoKODAj0ZBJeszcX
"""

print ("Hello World")

print ("\n--- Batas --- \n")




print ("\n Tipe data \n")

teks = "Halo Dunia"
angka = 12
desimal = 12.23
char = 'A'
cek = True

detail = f"""
- Teks     : {teks}
- Angka    : {angka}
- Desimal  : {desimal}
- Char     : {char}
- Cek      : {cek}
"""

print (detail)

print ("\n--- Batas --- \n")




print ("\n Variabel dasar \n")

nama = "Habib Muzakki"
alumni = "MAN 2 KOTA SERANG"
alumni_kelas = "12 Agama"
angkatan = "34 Acsendria"
lomba = "Finalis OSN-K Informatika 2025"
coding = "HTML, CSS, JavaScript dan Python"
fans = "JKT48"
oshi = [
    "1. Michie JKT48 (UTAMA)",
    "2. Gracie JKT48 (UTAMA)",
    "3. Fritzy JKT48 (UTAMA)",
    "4. Lily JKT48 (UTAMA)",
    "5. Anindya JKT48 (UTAMA)",
    "6. Christy JKT48 (UTAMA)",
    "7. Freya JKT48 (UTAMA)",
    "8. Olla JKT48",
    "9. Jessi JKT48",
    "10. Fiony JKT48",
    "11. Muthe JKT48",
    "12. Marsha JKT48",
    "13. Eli JKT48",
    "14. Mikaela JKT48",
    "15. Ekin JKT48",
]


profil = f"""
- Nama       : {nama}
- Alumni     : {alumni}
- Kelas      : {alumni_kelas}
- Angkatan   : {angkatan}
- Lomba      : {lomba}
- Coding     : {coding}
- Fans       : {fans}
- Oshi JKT48 :
"""

print (profil)


for a in oshi:
    print (a)



print ("\n --- Batas --- \n")




print ("\n Operasi dasar \n")

a = 10
b = 5

detail = f"""
- Operasi Aritmatika

- Tambah  = {a + b}
- Kurang  = {a - b}
- Kali    = {a * b}
- Pangkat = {a ** b}
- Bagi    = {a / b}
- Sisa    = {a % b}

--------------------

- Operasi Perbandingan

- Hasil = {a > b}
- Hasil = {a < b}
- Hasil = {a >= b}
- Hasil = {a <= b}
- Hasil = {a == b}
- Hasil = {a != b}

-------------------

- Operasi Logika

- Hasil = {a > b and a < b}
- Hasil = {a > b or a < b}
- Hasil = {not a}
- Hasil = {not b}
- Hasil = {not (a < b)}
- Hasil = {not (a > b)}

--------------------------

"""

print (detail)


print ("\n --- Batas --- \n")




print ("\n Match Case \n")

warna = "Merah"

match (warna):
    case "Merah":
        print ("Merah")
    case _:
        print ("Warna Lain")


print ("\n --- Batas --- \n")




print ("\n Match Case 1 \n")

kondisi = 3

match (kondisi):
    case 1:
        print ("Oke")
    case 2:
        print ("Setengah Oke")
    case 3:
        print ("Kurang Oke")
    case 4:
        print ("Parah banget")
    case 5:
        print ("Damn parah")
    case _:
        print ("Biasa aja")


print ("\n --- Batas --- \n")




print ("\n Percabangan Dasar \n")

a = 9

if a > 5:
    print (f"Hasil besar, angka = {a}")
else:
    print (f"Hasil kecil, angka = {a}")


print ("\n --- Batas --- \n")




print ("\n Percabangan Lanjutan \n")

c = 9

if c > 5:
    print (f"Hasil besar, angka = {c}")
elif c == 5:
    print (f"Hasil sama dengan, angka = {c}")
else:
    print (f"Hasil kecil, angka = {c}")


print ("\n --- Batas --- \n")




print ("\n Percabangan Lanjutan 1 \n")

d = 3

if d > 5:
    print (f"Hasil besar, angka d = {d}")
elif d < 5:
    print (f"Hasil kecil, angka d = {d}")
else:
    print (f"Hasil sama dengan, angka d = {d}")


print ("\n --- Batas --- \n")




print ("\n Percabangan Ladder \n")

nilai = 90

if nilai >= 90:
    print (f"Nilai A, nilai = {nilai}")
elif nilai >= 80:
    print (f"Nilai B, nilai = {nilai}")
elif nilai >= 70:
    print (f"Nilai C, nilai = {nilai}")
elif nilai >= 60:
    print (f"Nilai D, nilai = {nilai}")
else:
    print (f"Nilai E, nilai = {nilai}")


print ("\n --- Batas --- \n")




print ("\n Nested If 1 \n")

usia = 15
cek = True

if cek == True:
    if usia >= 15:
        print (f"Usia kamu oke kok, usia = {usia}")
    elif usia <= 15:
        print (f"Usia kamu belum, usia = {usia}")
else:
    print (f"Sama saja, usia = {usia}")


print ("\n ---Batas --- \n")




print ("\n Nested If 2 \n")

usia = 13
cek = True

if usia >= 15:
    if cek == True:
        print (f"Nilai usia oke, usia = {usia}")
    else:
        print (f"Nilai usia belum oke, usia = {usia}")
else:
    print (f"Belum sama sekali, usia = {usia}")


print ("\n --- batas --- \n")




print ("\n Percabangan Nested If Majemuk Kompleks \n")

uang = 10000
usia = 19
cek = True

if usia >= 25 and uang >= 500000:
    if cek == True:
        print (f"Sangat oke dalam cari uang, usia = {usia}, uang = {uang}")
    elif usia <= 25 and uang <= 500000:
        print (f"Belum oke dalam cari uang, usia = {usia}, uang = {uang}")
    else:
        print (f"Masih dibawah umur dan belum layak, usia = {usia}, uang = {uang}")
else:
    print (f"Masih kecil dan balita, usia = {usia}, uang = {uang}")


print ("\n --- batas --- \n")




print ("\n Percabangan Nested If Majemuk Kompleks 1 \n")

usia = 30
uang = 50000
cek = True

if usia >= 25 and uang >= 500000:
    if cek == True:
        print (f"Usia dan uang oke kok, usia = {usia} dan uang = {uang}")
    elif usia <= 25 and uang <= 500000:
        print (f"Belum cukup dong, usia = {usia} dan uang = {uang}")
    else:
        print (f"Belum ada uang, usia = {usia} dan uang = {uang}")
else:
    print (f"Masih ada peluang kok, usia = {usia} dan uang = {uang}")


print ("\n --- batas --- \n")




print ("\n For Perulangan 1\n")

for a in range (11):
    print (f"Urutan ke - {a}")


print ("\n --- Batas --- \n")




print ("\n For Perulangan 2 \n")

for b in range (15, 26):
    print (f"Urutan ke - {b}")


print ("\n --- Batas --- \n")




print ("\n For Perulangan 3 \n")

for c in range (20, 36):
    print (f"Urutan ke - {c}")


print ("\n --- Batas --- \n")




print ("\n While Perulangan \n")

a = 10

while a < 21:
    print (f"Urutan ke - {a}")
    a += 1
    
print ("\n --- Batas --- \n")




print ("\n While Perulangan 1 \n")

b = 30

while b < 51:
    print (f"Urutan ke - {b}")
    b += 1

print ("\n --- Batas --- \n")