# -*- coding: utf-8 -*-
"""Input_dan_Output

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BZwaatHrGIJaYI9-Lk3VLFZhAwulhDJl
    
"""

print ("\n Input dan Output 1 \n")

nama = input ("Masukkan nama kamu :")

if nama == "Habib":
    print ("Halo Habib")
elif nama == "Denis":
    print ("Halo Denis")
else:
    print ("Halo orang lain")
    
    
print ("\n--- Batas --- \n")




print ("\n Input dan Output 2 \n")

nama = input ("Nama kamu siapa ? ")
asal = input ("Asal kamu darimana ?")
usia = int (input ("usia kamu berapa ?"))

if usia == 25:
    print ("usia anda 25 tahun")
elif usia == 24:
    print ("usia anda 24 tahun")
elif usia == 23:
    print ("usia anda 23 tahun ")
elif usia == 22:
    print ("usia anda 22 tahun")
elif usia == 21:
    print ("usia anda 21 tahun")
elif usia == 20:
    print ("usia anda 20 tahun")
elif usia == 19:
    print ("usia anda 19 tahun")
elif usia == 18:
    print ("usia anda 18 tahun")
elif usia == 17:
    print ("usia anda 17 tahun")
elif usia == 16:
    print ("usia anda 16 tahun")
elif usia == 15:
    print ("usia anda 15 tahun")
elif usia == 14:
    print ("usia anda 14 tahun ")
elif usia == 13:
    print ("usia anda 13 tahun")
elif usia == 12:
    print ("usia anda 12 tahun")
elif usia == 11:
    print ("usia anda 11 tahun")
else:
    print ("Usia anda dibawah 10 tahun")

detail = f"""
- Nama  : {nama}
- Usia  : {usia}

"""

print (detail)


print ("\n--- Batas --- \n")
